<?php

namespace My\PrzepisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrzepisRespository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrzepisRespository extends EntityRepository
{
}
